version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181

  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.219 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

